version: 2

builds:
  - goos:
      - linux
      - darwin
      - windows
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.BuildDate={{.Date}}
